/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manage;

import CONFIG.DBCONNECTOR;
import CONFIG.Session;
import CONFIG.passwordHash;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ADMIN
 */
public class changepass extends javax.swing.JInternalFrame {

    /**
     * Creates new form changepass
     */
    public changepass() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        user_name = new app.bolivia.swing.JCTextField();
        line = new javax.swing.JLabel();
        e_mail = new app.bolivia.swing.JCTextField();
        line1 = new javax.swing.JLabel();
        con_tact = new app.bolivia.swing.JCTextField();
        line3 = new javax.swing.JLabel();
        sta_tus = new app.bolivia.swing.JCTextField();
        line5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        oldpass = new app.bolivia.swing.JCTextField();
        line2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newpass = new app.bolivia.swing.JCTextField();
        line4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        conpass = new app.bolivia.swing.JCTextField();
        line6 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 80, 80));

        iddisplay.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(255, 255, 255));
        iddisplay.setText("(user)");
        jPanel2.add(iddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 32));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email   ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 32));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contact  ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 32));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("  Status  ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 80, 32));

        user_name.setBackground(new java.awt.Color(0, 204, 0));
        user_name.setBorder(null);
        user_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_name.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        user_name.setOpaque(false);
        user_name.setPlaceholder("enter isbn");
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel2.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, -1));

        line.setForeground(new java.awt.Color(25, 20, 20));
        line.setText("_______________________________");
        jPanel2.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 30));

        e_mail.setBackground(new java.awt.Color(0, 204, 0));
        e_mail.setBorder(null);
        e_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e_mail.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        e_mail.setOpaque(false);
        e_mail.setPlaceholder("enter book title");
        e_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                e_mailKeyReleased(evt);
            }
        });
        jPanel2.add(e_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        line1.setForeground(new java.awt.Color(25, 20, 20));
        line1.setText("_______________________________");
        jPanel2.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, 30));

        con_tact.setBackground(new java.awt.Color(0, 204, 0));
        con_tact.setBorder(null);
        con_tact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        con_tact.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        con_tact.setOpaque(false);
        con_tact.setPlaceholder("enter edition");
        con_tact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_tactActionPerformed(evt);
            }
        });
        con_tact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                con_tactKeyTyped(evt);
            }
        });
        jPanel2.add(con_tact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, -1));

        line3.setForeground(new java.awt.Color(25, 20, 20));
        line3.setText("_______________________________");
        jPanel2.add(line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, 30));

        sta_tus.setBackground(new java.awt.Color(0, 204, 0));
        sta_tus.setBorder(null);
        sta_tus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sta_tus.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        sta_tus.setOpaque(false);
        sta_tus.setPlaceholder("enter edition");
        sta_tus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sta_tusActionPerformed(evt);
            }
        });
        sta_tus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sta_tusKeyTyped(evt);
            }
        });
        jPanel2.add(sta_tus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        line5.setForeground(new java.awt.Color(25, 20, 20));
        line5.setText("_______________________________");
        jPanel2.add(line5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account Information");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Change Password Account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Old Password  ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, 32));

        oldpass.setBorder(null);
        oldpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oldpass.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        oldpass.setOpaque(false);
        oldpass.setPlaceholder("enter isbn");
        jPanel1.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        line2.setForeground(new java.awt.Color(25, 20, 20));
        line2.setText("_______________________________");
        jPanel1.add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 200, 30));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("New Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 32));

        newpass.setBorder(null);
        newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpass.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        newpass.setOpaque(false);
        newpass.setPlaceholder("enter book title");
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        newpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newpassKeyReleased(evt);
            }
        });
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        line4.setForeground(new java.awt.Color(25, 20, 20));
        line4.setText("_______________________________");
        jPanel1.add(line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 30));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Confirm Password ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 180, 32));

        conpass.setBorder(null);
        conpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conpass.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        conpass.setOpaque(false);
        conpass.setPlaceholder("enter edition");
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        conpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conpassKeyTyped(evt);
            }
        });
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 210, -1));

        line6.setForeground(new java.awt.Color(25, 20, 20));
        line6.setText("_______________________________");
        jPanel1.add(line6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 200, 30));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(0, 204, 0));
        rSMaterialButtonCircle2.setText("Change");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void e_mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_mailKeyReleased

    }//GEN-LAST:event_e_mailKeyReleased

    private void con_tactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_tactKeyTyped

    }//GEN-LAST:event_con_tactKeyTyped

    private void sta_tusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sta_tusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sta_tusActionPerformed

    private void sta_tusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sta_tusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sta_tusKeyTyped

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void newpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpassKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassKeyReleased

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void conpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conpassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassKeyTyped

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        try{
            DBCONNECTOR dbc = new DBCONNECTOR();
            Session sess = Session.getInstance();

            String query = "SELECT * FROM user WHERE user_id = '" + sess.getUid() + "'";
            ResultSet rs = dbc.getData(query);
            if(rs.next()){
                String oldbpass = rs.getString("password");
                String oldhash = passwordHash.hashPassword(oldpass.getText());

                if(oldbpass.equals(oldhash)){
                    String npass = passwordHash.hashPassword(newpass.getText());
                    dbc.updateData("UPDATE user SET password = '" + npass + "'");
                    JOptionPane.showMessageDialog(null, "Successfully Updated");

                }else{
                    JOptionPane.showMessageDialog(null, "Old password is incorrect");
                }
            }
        }catch(SQLException | NoSuchAlgorithmException ex){
            System.out.println(""+ex);

        }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
               
                iddisplay.setText("USER ID: "+sess.getUid());
                user_name.setText(""+sess.getUN());
                user_name.setEnabled(false);
                e_mail.setText(""+sess.getEMAIL());
                e_mail.setEnabled(false);
                con_tact.setText(""+sess.getCONTACT());
                con_tact.setEnabled(false);
                sta_tus.setText(""+sess.getStatus());
                sta_tus.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void con_tactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_tactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_tactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField con_tact;
    private app.bolivia.swing.JCTextField conpass;
    private app.bolivia.swing.JCTextField e_mail;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel line3;
    private javax.swing.JLabel line4;
    private javax.swing.JLabel line5;
    private javax.swing.JLabel line6;
    private app.bolivia.swing.JCTextField newpass;
    private app.bolivia.swing.JCTextField oldpass;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField sta_tus;
    private app.bolivia.swing.JCTextField user_name;
    // End of variables declaration//GEN-END:variables
}
