/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryManagementSystem;

import CONFIG.DBCONNECTOR;
import internalpage.dashabord;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.*;
import java.awt.print.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class studentdet extends javax.swing.JFrame {
DefaultTableModel model;
 
    public studentdet() {
        initComponents();
         displayData();
    }
    
     public void search(String str){
    model = (DefaultTableModel) studentdet.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    studentdet.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    }
                 
       public void filter(String qry ){
             model = (DefaultTableModel) studentdet.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
         studentdet.setRowSorter(trs);
       
         if(qry =="ALL"){
        studentdet.setRowSorter(trs);
         }else{
         trs.setRowFilter(RowFilter.regexFilter(qry));
         }
       
       }
     
     public void filter1(String yr ){
             model = (DefaultTableModel) studentdet.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
         studentdet.setRowSorter(trs);
       
         if(yr =="ALL"){
        studentdet.setRowSorter(trs);
         }else{
         trs.setRowFilter(RowFilter.regexFilter(yr));
         }
       
       }
     
     
     
  public void close(){
        this.dispose();
        DASHBOARD dash = new DASHBOARD();
        dash.setVisible(true);
        dashabord up = new dashabord();
        dash.maindesk.add(up).setVisible(true);
    }
    public void displayData(){
        try{
       
            DBCONNECTOR dbc = new DBCONNECTOR();
            ResultSet rs = dbc.getData("SELECT * FROM student_details");
            studentdet.setModel(DbUtils.resultSetToTableModel(rs));
       DefaultTableModel model = (DefaultTableModel) studentdet.getModel();
    String[] columnIdentifiers = {"ID", "Name", "Lastname", "Course","Year","Contact"};
    model.setColumnIdentifiers(columnIdentifiers);
    
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        FILTER = new javax.swing.JComboBox<>();
        YRFILTER = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentdet = new rojeru_san.complementos.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        BACK = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBorder(null);
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        search.setPlaceholder("SEARCH");
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, 20));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(153, 0, 0));
        rSMaterialButtonCircle2.setText("PRINT");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 110, 40));

        FILTER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "BSIT", "BSHM", "BEED", "BSBA", "BSTM", "BSCRIM", " " }));
        FILTER.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FILTERItemStateChanged(evt);
            }
        });
        jPanel1.add(FILTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 110, 30));

        YRFILTER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "1st", "2nd", "3rd", "4th", " ", " " }));
        YRFILTER.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                YRFILTERItemStateChanged(evt);
            }
        });
        jPanel1.add(YRFILTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 110, 30));

        studentdet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "LASTNAME", "COURSE", "YEAR", "CONTACT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentdet.setColorBackgoundHead(new java.awt.Color(0, 204, 0));
        studentdet.setGridColor(new java.awt.Color(255, 255, 255));
        studentdet.setGrosorBordeFilas(0);
        jScrollPane1.setViewportView(studentdet);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 920, 440));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduation.png"))); // NOI18N
        jLabel2.setText("STUDENT TABLE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 440, 70));

        BACK.setBackground(new java.awt.Color(153, 0, 0));
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
    }//GEN-LAST:event_BACKActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String seachst = search.getText();
        search(seachst);
    }//GEN-LAST:event_searchKeyReleased

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        MessageFormat head = new MessageFormat("STUDENT DETAILS");
        MessageFormat FOOT = new MessageFormat("Page{0, number , integer}");

        try {
            studentdet.print(JTable.PrintMode.NORMAL, head, FOOT);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "cannot print");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void FILTERItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FILTERItemStateChanged
     String qry = FILTER.getSelectedItem().toString();
     
        filter(qry); 
    }//GEN-LAST:event_FILTERItemStateChanged

    private void YRFILTERItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_YRFILTERItemStateChanged
        String yr = YRFILTER.getSelectedItem().toString();
        
        filter(yr);
    }//GEN-LAST:event_YRFILTERItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentdet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle BACK;
    private javax.swing.JComboBox<String> FILTER;
    private javax.swing.JComboBox<String> YRFILTER;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField search;
    private rojeru_san.complementos.RSTableMetro studentdet;
    // End of variables declaration//GEN-END:variables
}
